version: "3.7"
services:
  app:
    build:
      args:
        user: dummy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/www